sudo: required
services:
  - docker

before_install:
  - docker build -t ynvygy/docker-react -f Dockerfile.dev .

script:
  #- docker run ynvygy/docker-react npm run test -- --coverage
  - docker-run -e CI=true ynvygy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-992382519884"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
