sudo: required
services:
  - docker

before_install:
  - docker build -t ynvygy/docker-react -f Dockerfile.dev .

script:
  #- docker run ynvygy/docker-react npm run test -- --coverage
  - docker-run -e CI=true ynvygy/docker-react npm run test
